# In Case of settign up Environment copy this file to ~/

echo "Configuring .dotfiles..."

CONFIG=$HOME/.dotfiles/zsh/antigen.zsh
CONFIG_PATHS=$HOME/.dotfiles/zsh/paths.zsh
CONFIG_ALIAS=$HOME/.dotfiles/zsh/aliases.zsh

# Import Antigen to manage zsh
if [[ ! -a $CONFIG ]]; then
    echo "FATAL: Unable to load antigen.zsh!";
    echo -e "Expected location $CONFIG"
else 
    source $CONFIG
fi

# (1) Load the oh-my-zh lib
antigen use oh-my-zsh

# (2) Load Bundles 

### Shell Utilities
#zsh
antigen bundle ls
# antigen bundle zsh-history
# antigen bundle mafredi/zsh-zsync
# antigen bundle zsh-users/zsh-syntax-highlighting

# TMUX
antigen bundle tmux

# FileSystem 
# antigen bundle pj   # project jump
antigen bundle wd   # warp directory

# Git Plugins
antigen bundle git 
antigen bundle github

# Javscript Plugins
antigen bundle coffee
antigen bundle node
antigen bundle npm

# Python Plugins
antigen bundle pip
antigen bundle python

# Ruby 
antigen bundle gem

# Environment
# antigen bundle virtualenv
antigen bundle zsh-docker

# DB 
antigen bundle zpm-zsh/mysql-colorize

# Man pages
# antigen bundle bwana

# Note-taking
antigen bundle chipsenkbeil/zsh-notes

# OS specific plugins
case "$(uname -s)" in 
    Darwin*)
        antigen bundle brew
        antigen bundle osx
        antigen bundle zsh-apple-touchbar
        ;;
    Linux*)
        # Got Nothing at this point...
        ;;
    Cygwin*)
        #antigen bundle cygwin
        ;;

esac

# (3) Set Theme 
# antigen theme denysdovhan/spaceship-prompt
 antigen theme cdimascio/lambda-zsh-theme
# antigen theme norm
# antigen theme obraun
# antigen theme theunraveler
# antigen theme trapd00r
# antigen theme refined

# Fzf keybindings and completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# (4) Apply settinga to Antigen
antigen apply

clear 

# Custome Aliases 
if [[ -a $CONFIG_ALIAS ]]; then 
    source $CONFIG_ALIAS
else
    echo "WARNING: Custom Aliases not found!"
fi

# Custome Path Extensions
if [[ -a $CONFIG_PATHS ]]; then
    source $CONFIG_PATHS
else 
    echo "WARNING: Custom Paths not found!"
fi

